<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKtXVQ5U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKtXVQ5U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKtXVQ5U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKtXVQ5U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKtXVQ5U\App_KernelDevDebugContainer([
    'container.build_hash' => 'KtXVQ5U',
    'container.build_id' => '3f209188',
    'container.build_time' => 1628525363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKtXVQ5U');
